
files  = $(wildcard *.xml)
gmn := $(patsubst %.xml, %.gmn, $(files))

all : $(gmn)

clean :
	rm -f $(gmn)

%.gmn: %.xml
	xml2guido $< > $@


05_long_ago.gmn: 05_long_ago.xml
Alla_faglar.gmn: Alla_faglar.xml
Bug_mapping.gmn: Bug_mapping.xml
E_danza.gmn: E_danza.xml
Entonigt_ringer_den_lilla_klockan.gmn: Entonigt_ringer_den_lilla_klockan.xml
Kostas_score.gmn: Kostas_score.xml
La_sera.gmn: La_sera.xml
My_bonnie.gmn: My_bonnie.xml
Ojos_agules.gmn: Ojos_agules.xml
Repeat.gmn: Repeat.xml
Repeat1.gmn: Repeat1.xml
Ritmo_di_danza.gmn: Ritmo_di_danza.xml
Ritmo_di_danza1.gmn: Ritmo_di_danza1.xml
Sjosala_vals.gmn: Sjosala_vals.xml
Timesign.gmn: Timesign.xml
Tos_och_mus.gmn: Tos_och_mus.xml
Triolet.gmn: Triolet.xml
Triolet1.gmn: Triolet1.xml
jazz.gmn: jazz.xml
jumps.gmn: jumps.xml
jumps4.gmn: jumps4.xml
scorev2.gmn: scorev2.xml
