#!/usr/bin/env python3

# Helper script to be put in /usr/bin/ or a similar location
# calling the appropriate python tool

# Copyright (C) 2008-2011 Brailcom, o.p.s
# Copyright (C) 2012 Christopher Brannon <chris@the-brannons.com>
#
# This program is free software; you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation; either version 2 of the License, or (at your option) any later
# version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE.  See the GNU General Public License for more details (file
# COPYING in the root directory).
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

import speechd_config

if __name__=='__main__':
    import sys
    sys.exit(speechd_config.main())
