// Don't edit. This file is generated by gen_gperf_symbol_pcm.pl
#ifndef ZH_SYMBOL_MAP_H
#define ZH_SYMBOL_MAP_H

#include "phonetic_symbol.h"
class ZH_PHash {
private:
  static inline unsigned int hash (const char *str, unsigned int len);
public:
  static ekho::SymbolCode* in_word_set (const char *str, unsigned int len);
};

#endif
